import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';

import { validateConfig } from '../core/config-schema.js';
import { discoverModules, loadModule } from '../core/module-loader.js';
import { loadThemeTokens, buildThemeCss } from '../core/theme-tokens.js';
import { renderAll } from '../core/render-pipeline.js';
import { buildDocument, GENERATED_MARKER_PREFIX } from '../core/html-shell.js';
import { copyModuleAssets } from '../core/asset-pipeline.js';

const ROOT = process.cwd();
const VERSION = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8')).version;

export async function run({ force = false } = {}) {
    const configPath = path.join(ROOT, 'config', 'site.config.json');
    const config = JSON.parse(readFileSync(configPath, 'utf8'));
    validateConfig(config);

    const modulesRoot = path.join(ROOT, 'modules');
    const manifests = discoverModules(modulesRoot);

    // "infra"/"chrome" modules (core-assets, header, hero, footer) are always
    // included when present -- they aren't part of the user-selectable
    // content-section set in config.modules.enabled.
    const idsToLoad = [];
    for (const [id, manifest] of manifests) {
        if (manifest.kind === 'infra' || manifest.kind === 'chrome') {
            idsToLoad.push(id);
        }
    }
    for (const id of config.modules.order) {
        if (!manifests.has(id)) {
            throw new Error(`config.modules.order references unknown module "${id}" (no modules/${id}/module.json found).`);
        }
        idsToLoad.push(id);
    }

    const loaded = [];
    for (const id of idsToLoad) {
        loaded.push(await loadModule(manifests.get(id)));
    }

    const tokens = loadThemeTokens(path.join(ROOT, 'themes'), config.theme.preset);
    const themeCss = buildThemeCss(tokens, config.theme.overrides || {});

    const { rendered, styleText, scriptText } = renderAll(loaded, config);

    const html = buildDocument({
        config,
        version: VERSION,
        themeCss,
        styleText,
        scriptText,
        rendered,
    });

    const outputPath = path.join(ROOT, 'index.html');
    if (existsSync(outputPath) && !force) {
        const existing = readFileSync(outputPath, 'utf8');
        if (!existing.includes(GENERATED_MARKER_PREFIX)) {
            throw new Error(
                `${outputPath} already exists and wasn't generated by SiteKit. Refusing to overwrite it -- pass --force if you're sure.`
            );
        }
    }
    writeFileSync(outputPath, html);

    const copiedAssetModules = copyModuleAssets(loaded, ROOT);

    console.log(`Generated ${outputPath}`);
    console.log(`Modules rendered: ${rendered.map((r) => r.id).join(', ') || '(none)'}`);
    console.log(`Assets copied for: ${copiedAssetModules.join(', ') || '(none)'}`);
}
