import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';

import { validateConfig } from '../core/config-schema.js';
import { discoverModules, loadModule, prepareModules, resolveActiveModuleIds, validateModuleConfiguration } from '../core/module-loader.js';
import { loadThemeTokens, buildThemeCss } from '../core/theme-tokens.js';
import { buildFontTags } from '../core/font-tags.js';
import { renderAll } from '../core/render-pipeline.js';
import { buildDocument, GENERATED_MARKER_PREFIX } from '../core/html-shell.js';
import { copyModuleAssets, copyThemeFonts, generateModuleAssets, removeInactiveModuleAssets } from '../core/asset-pipeline.js';
import { buildIconSubset } from '../core/icon-subset.js';
import { throwForProblems, validateGeneratedAssetContracts, validateModuleContent, validateReferencedAssets } from '../core/content-validation.js';

const ROOT = process.cwd();
const VERSION = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8')).version;

export async function run({ force = false } = {}) {
    const configPath = path.join(ROOT, 'site.config.json');
    const config = JSON.parse(readFileSync(configPath, 'utf8'));
    validateConfig(config);

    const modulesRoot = path.join(ROOT, 'modules');
    const manifests = discoverModules(modulesRoot);
    validateModuleConfiguration(manifests, config);

    // "infra"/"chrome" modules (core-assets, header, hero, footer) are always
    // included when present -- they aren't part of the user-selectable
    // content-section list in config.modules.order. "extension" modules
    // (favicon/app-icon, og-meta, dark-mode, ...) follow the same
    // present-on-disk-means-active rule, but can be individually opted out
    // via config.extensions.<id> = false (e.g. once favicon generation is
    // heavy enough to want explicit control).
    const idsToLoad = resolveActiveModuleIds(manifests, config);

    const loaded = [];
    for (const id of idsToLoad) {
        loaded.push(await loadModule(manifests.get(id)));
    }

    throwForProblems(validateModuleContent(loaded));

    const preparationWarnings = await prepareModules(loaded, config);
    preparationWarnings.forEach((warning) => console.warn(`Warning: ${warning}`));

    const tokens = loadThemeTokens(path.join(ROOT, 'themes'), config.theme.preset);
    const themeOverrides = config.theme.overrides || {};
    const themeCss = buildThemeCss(tokens.colors, themeOverrides);
    const mergedThemeColors = { ...tokens.colors, ...themeOverrides };

    // Font provider/baseUrl can be overridden per-site without forking the
    // theme (config.theme.fontOverrides); families/files always stay
    // theme-owned, since swapping a CDN doesn't change which font files
    // exist, only where they're fetched from.
    const fontOverrides = config.theme.fontOverrides || {};
    const mergedFonts = { ...(tokens.fonts || {}), ...fontOverrides };
    if (mergedFonts.provider === 'self-hosted' && !fontOverrides.baseUrl) {
        const copiedBaseUrl = copyThemeFonts(path.join(ROOT, 'themes'), config.theme.preset, ROOT);
        if (copiedBaseUrl) mergedFonts.baseUrl = copiedBaseUrl;
    }
    const fontTags = buildFontTags(mergedFonts);

    const { rendered, styleText, scriptText, globalsCss } = renderAll(loaded, config, {
        themeColors: mergedThemeColors,
    });
    throwForProblems(validateReferencedAssets(loaded));

    const html = buildDocument({
        config,
        version: VERSION,
        themeCss,
        styleText,
        scriptText,
        globalsCss,
        rendered,
        fontTags,
    });

    const outputPath = path.join(ROOT, 'index.html');
    if (existsSync(outputPath) && !force) {
        const existing = readFileSync(outputPath, 'utf8');
        if (!existing.includes(GENERATED_MARKER_PREFIX)) {
            throw new Error(
                `${outputPath} already exists and wasn't generated by SiteKit. Refusing to overwrite it -- pass --force if you're sure.`
            );
        }
    }
    writeFileSync(outputPath, html);

    const removedAssetModules = removeInactiveModuleAssets(manifests, idsToLoad, ROOT);
    const copiedAssetModules = copyModuleAssets(loaded, ROOT);
    const generatedAssetModules = await generateModuleAssets(loaded, ROOT, config, { themeColors: mergedThemeColors });
    throwForProblems(validateGeneratedAssetContracts(loaded, { requireFiles: true }));

    // Tabler icon subsetting runs AFTER copyModuleAssets (which already
    // skipped the vendored full font/map via core-assets' assetsExclude --
    // see asset-pipeline.js) and writes the real subset straight into that
    // same output folder, since it's build output, not authored source.
    const coreAssetsModule = loaded.find((m) => m.id === 'core-assets');
    let iconSubsetInfo = '(none)';
    if (coreAssetsModule) {
        const subset = buildIconSubset({ rendered, loadedModules: loaded, coreAssetsDir: coreAssetsModule.dir });
        if (subset) {
            const { cssText, woff2Buffer } = await subset.build();
            const fontsOutDir = path.join(ROOT, 'assets', 'core-assets', 'fonts');
            mkdirSync(fontsOutDir, { recursive: true });
            writeFileSync(path.join(fontsOutDir, 'tabler-icons-subset.min.css'), cssText);
            writeFileSync(path.join(fontsOutDir, 'tabler-icons-subset.woff2'), woff2Buffer);
            iconSubsetInfo = `${subset.usedClasses.length} glyphs, ${woff2Buffer.length} bytes`;
        }
    }

    console.log(`Generated ${outputPath}`);
    console.log(`Modules rendered: ${rendered.map((r) => r.id).join(', ') || '(none)'}`);
    console.log(`Assets copied for: ${copiedAssetModules.join(', ') || '(none)'}`);
    console.log(`Assets generated for: ${generatedAssetModules.join(', ') || '(none)'}`);
    if (removedAssetModules.length) console.log(`Stale assets removed for: ${removedAssetModules.join(', ')}`);
    console.log(`Tabler icon subset: ${iconSubsetInfo}`);
}
