import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import subsetFont from 'subset-font';

const ICON_CLASS_RE = /\bti-[a-z0-9-]+\b/g;

const CSS_HEADER = `/*!
 * Tabler Icons -- build-time subset, generated by SiteKit's icon-subset.js.
 * Do not hand-edit: this file is regenerated by every "npm run generate"
 * from modules/core-assets/assets/fonts/{tabler-icons-full.woff2,tabler-icons-map.json}
 * and whichever .ti-* classes actually appear in the rendered page.
 */`;

/**
 * Scans every rendered module's html (and defensively each loaded module's
 * clientText, in case a future live-mode module injects an icon class only
 * client-side) for used .ti-* classes, subsets the vendored full Tabler
 * webfont down to just those glyphs via `subset-font` (a devDependency --
 * dev-time only, doesn't touch SiteKit's zero-*runtime*-dependency goal),
 * and generates a matching minimal CSS file in the same format as the icon
 * font's own upstream distribution.
 *
 * Returns null if core-assets (or its vendored font/map) isn't present --
 * callers should treat that as "nothing to do", not an error, since a site
 * that disables core-assets simply has no icon font to subset.
 */
export function buildIconSubset({ rendered, loadedModules, coreAssetsDir }) {
    const fontPath = path.join(coreAssetsDir, 'assets', 'fonts', 'tabler-icons-full.woff2');
    const mapPath = path.join(coreAssetsDir, 'assets', 'fonts', 'tabler-icons-map.json');
    if (!existsSync(fontPath) || !existsSync(mapPath)) return null;

    const codepointMap = JSON.parse(readFileSync(mapPath, 'utf8'));

    const haystacks = rendered.map((r) => r.html || '').concat(loadedModules.map((m) => m.clientText || ''));
    const usedClasses = new Set();
    for (const text of haystacks) {
        for (const match of text.matchAll(ICON_CLASS_RE)) {
            const name = match[0].slice(3); // strip "ti-"
            if (Object.prototype.hasOwnProperty.call(codepointMap, name)) {
                usedClasses.add(name);
            }
        }
    }

    const sortedNames = [...usedClasses].sort();
    const chars = sortedNames.map((name) => String.fromCodePoint(codepointMap[name])).join('');

    return {
        usedClasses: sortedNames,
        async build() {
            const fullFontBuffer = readFileSync(fontPath);
            const subsetBuffer = chars
                ? await subsetFont(fullFontBuffer, chars, { targetFormat: 'woff2' })
                : await subsetFont(fullFontBuffer, '', { targetFormat: 'woff2' });

            const rules = sortedNames.map(
                (name) => `.ti-${name}:before{content:"\\${codepointMap[name].toString(16)}"}`
            );
            const cssText =
                `${CSS_HEADER}\n` +
                `@font-face{font-family:"tabler-icons";font-style:normal;font-weight:400;font-display:swap;src:url("./tabler-icons-subset.woff2") format("woff2")}\n` +
                `.ti{font-family:"tabler-icons" !important;speak:none;font-style:normal;font-weight:normal;font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}\n` +
                rules.join('\n') +
                '\n';

            return { cssText, woff2Buffer: subsetBuffer };
        },
    };
}
